# Generated by Django 4.1.1 on 2022-10-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('parks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='main_app.parks')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sites', models.ManyToManyField(to='main_app.site')),
            ],
        ),
    ]
